### ISSUE TITLE
Not working when adding $HOME/bin to PATH

### ISSUE THREAD

**Issue by seenickcode** [shinokada/awesome#1]
Looks like I had to use this to get it working: 

`export PATH=$HOME/.local/share/bin:$PATH`

**Comment by shinokada** [comment]
Yes. It's in the README.
Thanks.

**Comment by seenickcode** [comment]
Forgot to mention...the installation script provides incorrect directions, actually:

`export PATH=$HOME/bin:$PATH`

```
❯ curl -s https://raw.githubusercontent.com/shinokada/awesome/main/install | bash -s install

/Users/seenickcode/.local/share/awesome directory is created.
/Users/seenickcode/.local/share/bin directory is created.
Cloning into 'awesome'...
remote: Enumerating objects: 640, done.
remote: Counting objects: 100% (142/142), done.
remote: Compressing objects: 100% (103/103), done.
remote: Total 640 (delta 86), reused 93 (delta 38), pack-reused 498
Receiving objects: 100% (640/640), 3.19 MiB | 15.39 MiB/s, done.
Resolving deltas: 100% (394/394), done.
awesome installation completed.
Add the following to your your terminal config file, such as .zshrc or .bashrc.
export PATH=$HOME/bin:$PATH
Try awesome -h or which awesome.
```

**Comment by shinokada** [comment]
Ok, thank you for the catch. I will update it.

**Comment by seenickcode** [comment]
Thanks!

On July 14, 2021, Sean Pianka ***@***.***> wrote:
> Ok, thank you for the catch. I will update it.
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/shinokada/awesome/issues/1#issuecomment-880200034>,
or unsubscribe <https://github.com/notifications/unsubscribe-
auth/AAASQOO4A2Z5IYII464L4UTTXX2C5ANCNFSM5ALLAMHA>.
