### ISSUE TITLE
[BUG]: /usr/bin/env errors

### ISSUE THREAD

**Issue by nxuv** [shinokada/awesome#7]
### Description of the bug

awesome --help
/usr/bin/env: ‘bash\r’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines

### Steps To Reproduce

curl -s https://raw.githubusercontent.com/shinokada/awesome/main/install | bash -s install
awesome --help

### Additional Information

Distro: Manjaro Linux 
Kernel: 5.15.78-1-MANJARO 
Shell: bash 5.1.16

**Comment by shinokada** [comment]
Can you run it in a new terminal or source your bashrc?

```
. ~/.bashrc
```
